'use client'

import { useState } from 'react'
import QRCode from 'react-qr-code'
import { Tag, X, Printer } from 'lucide-react'

interface ArticleItem {
  id: string
    service_name: string
      quantity: number
        article_code?: string
          notes?: string
          }
          
          interface Props {
            items: ArticleItem[]
              orderNumber: string
                pressingName: string
                  trackingToken?: string
                  }
                  
                  export default function ArticleLabels({ items, orderNumber, pressingName, trackingToken }: Props) {
                    const [open, setOpen] = useState(false)
                    
                      if (items.length === 0) return null
                      
                        const trackBase = typeof window !== 'undefined' ? `${window.location.origin}/track/` : '/track/'
                          const trackUrl = trackingToken ? `${trackBase}${trackingToken}` : ''
                          
                            const expandedLabels: { item: ArticleItem; index: number }[] = []
                              items.forEach(item => {
                                  for (let i = 0; i < item.quantity; i++) {
                                        expandedLabels.push({ item, index: i + 1 })
                                            }
                                              })
                                              
                                                const handlePrint = () => {
                                                    const w = window.open('', '_blank', 'width=800,height=600')
                                                        if (!w) return
                                                            const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
                                                            <title>Etiquettes - ${orderNumber}</title>
                                                            <style>
                                                              * { margin: 0; padding: 0; box-sizing: border-box; }
                                                                body { font-family: Arial, sans-serif; background: white; }
                                                                  .grid { display: flex; flex-wrap: wrap; gap: 4px; padding: 4px; }
                                                                    .label { width: 48mm; min-height: 25mm; border: 1px dashed #aaa; border-radius: 4px; padding: 3mm; page-break-inside: avoid; background: white; display: flex; flex-direction: column; justify-content: space-between; }
                                                                      .top { display: flex; justify-content: space-between; align-items: flex-start; }
                                                                        .info { flex: 1; }
                                                                          .pressing { font-size: 6pt; color: #888; text-transform: uppercase; letter-spacing: 0.3px; }
                                                                            .order { font-size: 7pt; font-family: monospace; color: #3b82f6; }
                                                                              .code { font-size: 10pt; font-family: monospace; font-weight: bold; color: #1e3a8a; background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 2px; padding: 1px 4px; display: inline-block; margin: 2px 0; }
                                                                                .service { font-size: 8pt; font-weight: bold; color: #111; }
                                                                                  .qty { font-size: 7pt; color: #666; }
                                                                                    .qr { flex-shrink: 0; margin-left: 3mm; }
                                                                                      @media print { @page { margin: 2mm; size: auto; } body { margin: 0; } .grid { gap: 2px; padding: 0; } .label { border: 0.5pt dashed #ccc; } }
                                                                                      </style></head><body>
                                                                                      <div class="grid">
                                                                                      ${expandedLabels.map(({ item, index }) => {
                                                                                          const code = item.article_code || orderNumber
                                                                                            const qrValue = trackUrl || code
                                                                                              return `<div class="label"><div class="top"><div class="info"><div class="pressing">${pressingName}</div><div class="order">${orderNumber}</div><div class="code">${code}${item.quantity > 1 ? '-' + index : ''}</div><div class="service">${item.service_name}</div>${item.quantity > 1 ? '<div class="qty">' + index + '/' + item.quantity + '</div>' : ''}</div><div class="qr"><img src="https://api.qrserver.com/v1/create-qr-code/?size=80x80&data=${encodeURIComponent(qrValue)}" width="60" height="60" /></div></div></div>`
                                                                                              }).join('')}
                                                                                              </div>
                                                                                              <script>window.onload = function() { window.print(); }<\/script>
                                                                                              </body></html>`
                                                                                                  w.document.write(html)
                                                                                                      w.document.close()
                                                                                                        }
                                                                                                        
                                                                                                          return (
                                                                                                              <>
                                                                                                                    <button
                                                                                                                            onClick={() => setOpen(true)}
                                                                                                                                    className="flex items-center gap-1.5 text-xs text-indigo-600 hover:text-indigo-800 hover:bg-indigo-50 px-3 py-1.5 rounded-lg transition-colors border border-indigo-200"
                                                                                                                                          >
                                                                                                                                                  <Tag size={13} />
                                                                                                                                                          Etiquettes ({expandedLabels.length})
                                                                                                                                                                </button>
                                                                                                                                                                
                                                                                                                                                                      {open && (
                                                                                                                                                                              <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
                                                                                                                                                                                        <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col">
                                                                                                                                                                                                    <div className="flex items-center justify-between p-4 border-b">
                                                                                                                                                                                                                  <h3 className="font-semibold text-gray-900 flex items-center gap-2">
                                                                                                                                                                                                                                  <Tag size={16} className="text-indigo-600" />
                                                                                                                                                                                                                                                  Etiquettes - {orderNumber}
                                                                                                                                                                                                                                                                  <span className="text-sm font-normal text-gray-400">({expandedLabels.length} etiquette{expandedLabels.length > 1 ? 's' : ''})</span>
                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                              <button onClick={() => setOpen(false)} className="p-1.5 rounded-lg hover:bg-gray-100">
                                                                                                                                                                                                                                                                                                              <X size={18} />
                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                    <div className="overflow-y-auto flex-1 p-4">
                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-wrap gap-3">
                                                                                                                                                                                                                                                                                                                                                                                  {expandedLabels.map(({ item, index }, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                    const code = item.article_code || orderNumber
                                                                                                                                                                                                                                                                                                                                                                                                                      const qrValue = trackUrl || code
                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={`${item.id}-${index}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-48 border border-gray-200 rounded-xl p-3 bg-white shadow-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex justify-between items-start">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex-1 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[9px] text-gray-400 uppercase tracking-wider">{pressingName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[10px] font-mono text-blue-600 mt-0.5">{orderNumber}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="my-1.5 font-mono text-xs font-bold text-blue-900 bg-blue-50 border border-blue-200 rounded px-2 py-0.5 inline-block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {code}{item.quantity > 1 ? `-${index}` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs font-semibold text-gray-900 truncate">{item.service_name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {item.quantity > 1 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[10px] text-gray-400">{index}/{item.quantity}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="ml-2 shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <QRCode value={qrValue} size={50} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {item.notes && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[9px] text-amber-700 mt-1 truncate">{item.notes}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="p-4 border-t flex justify-end gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => setOpen(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Fermer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handlePrint}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="flex items-center gap-2 px-4 py-2 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Printer size={14} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Imprimer lot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '   </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
